version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
        networks:
            - incept_network
        init: true
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file:
            - .env
        restart: always
        volumes:
            - ${HOME}/data/mariadb:/var/lib/mysql
        networks:
            - incept_network
        init: true

volumes:
    mariadb:
        driver: local
        name: mariadb
        driver_opts:
            type: none
            device: ${HOME}/data/mariadb
            o: bind

networks:
    incept_network:
        name: inception
        driver: bridge
