version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
        networks:
            - incept_network
        init: true
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file:
            - .env
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - incept_network
        init: true
volumes:
    mariadb_data:
        name: mariadb_data

networks:
    incept_network:
        driver: bridge
