version: '3'

services:
    nginx:
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
        networks:
            - incept_network
    mariadb:
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - incept_network

volumes:
    mariadb_data:

networks:
    incept_network:
        driver: bridge
