version: '3'

services:
    custom-nginx:
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./html:/usr/share/nginx/html
        restart: always
    wordpress:
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        ports:
            - "8080:80"
